spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: oauth2
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
cookie:
  secure: ${COOKIE_USE_SECURE}